/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dale.superhairyjoe.entity;

import com.dale.superhairjoe.tile.Tile;
import com.dale.superhairyjoe.Game;
import com.dale.superhairyjoe.Handler;
import com.dale.superhairyjoe.Id;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author David
 */
public class Player extends Entity{


    private int frame = 0;
    private int frameDelay = 0;
    
    private boolean animate = false;
    
    
    public Player(int x, int y, int width, int height, boolean solid, Id id, Handler handler) {
        super(x, y, width, height, solid, id, handler);
        
        
        
        
        
        
    }
    
   
    public void tick()
    {
        x+=velX;
        y+=velY;
        
        //if (x<=0) x=0; removed to fall faster
        if (y<=0) y=0;
        //if (x + width >=Game.WIDTH * Game.SCALE) x=Game.WIDTH * Game.SCALE - width; removed to fall faster
        if (y + height >=Game.HEIGHT * Game.SCALE) y=Game.HEIGHT  * Game.SCALE - height;
        
        if (velX!=0) animate=true;
        else animate = false;
        
        for(Tile t:handler.tile)
        {
            if(!t.solid) break;
            if(t.getId()==Id.wall)
            {
                if(getBoundsTop().intersects(t.getBounds()))
                {
                    setvelY(0);
                    //y = t.getY() + t.height;
                    
                    if (jumping)
                    {
                        jumping=false;
                        gravity=0.8;
                        falling=true;
                    }
                    
                    
                } 
                if(getBoundsBottom().intersects(t.getBounds()))
                {
                    setvelY(0);
                    //y = t.getY() - t.height;
                    if(falling) falling=false;
                }
                else
                {
                    if(!falling && !jumping)
                    {
                        gravity=0.8;
                        falling=true;
                    }
                }
                
                
                
                
                if(getBoundsLeft().intersects(t.getBounds()))
                { 
                    setvelX(0);
                    x = t.getX() + t.width;
                }
                if(getBoundsRight().intersects(t.getBounds()))
                {
                    setvelX(0);
                    //x = t.getX() - t.width + 32 ;
                    x = t.getX() - t.width  ;
                }
            }
        }
        if (jumping)
           
        {
            gravity-=0.1;
            setvelY((int) -gravity);
            if(gravity<=0.0)
            {
                jumping = false;
                falling=true;
            }
        }
        if (falling)
        {
            gravity+=0.1;
            setvelY((int) gravity);
            
        }
        
        if(animate)
        {
            frameDelay++;
            if (frameDelay >= 3)
            {
                frame++;
                if (frame >= 4)
                {
                    frame=0;
                }
                frameDelay=0;
            }   
        }
        
        
    }
    
     public void render(Graphics g)
    {
        if(facing==0)
        {
      	g.drawImage(Game.player[frame+4].getBufferedImage(), x, y, width, height, null);
    	          
        }
        else if(facing==1)
        {
      	g.drawImage(Game.player[frame].getBufferedImage(), x, y, width, height, null);
    	          
        }   

    	 
        //g.setColor(Color.YELLOW);
        //g.fillRect(x , y  , width ,  height);
    
        //created with Homebrew excel tool 
    	/*
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 10, y + 0, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 12, y + 0, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 14, y + 0, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 15, y + 0, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 17, y + 0, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 19, y + 0, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 20, y + 0, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 21, y + 0, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 11, y + 1, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 1, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 13, y + 1, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 14, y + 1, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 15, y + 1, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 16, y + 1, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 17, y + 1, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 18, y + 1, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 19, y + 1, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 9, y + 2, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 10, y + 2, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 11, y + 2, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 12, y + 2, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 13, y + 2, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 14, y + 2, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 15, y + 2, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 16, y + 2, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 17, y + 2, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 18, y + 2, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 19, y + 2, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 20, y + 2, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 21, y + 2, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 8, y + 3, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 10, y + 3, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 11, y + 3, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 3, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 13, y + 3, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 14, y + 3, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 15, y + 3, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 16, y + 3, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 17, y + 3, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 18, y + 3, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 19, y + 3, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 20, y + 3, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 22, y + 3, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 9, y + 4, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 11, y + 4, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 4, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 13, y + 4, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 14, y + 4, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 15, y + 4, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 16, y + 4, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 17, y + 4, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 18, y + 4, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 19, y + 4, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 20, y + 4, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 21, y + 4, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 10, y + 5, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 11, y + 5, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 5, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 13, y + 5, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 14, y + 5, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 15, y + 5, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 16, y + 5, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 17, y + 5, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 18, y + 5, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 19, y + 5, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 20, y + 5, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 22, y + 5, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 9, y + 6, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 10, y + 6, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 11, y + 6, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 6, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 13, y + 6, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 14, y + 6, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 15, y + 6, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 16, y + 6, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 17, y + 6, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 18, y + 6, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 19, y + 6, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 20, y + 6, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 21, y + 6, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 10, y + 7, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 11, y + 7, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 7, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 13, y + 7, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 14, y + 7, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 15, y + 7, 1, 1);
        * g.setColor(Color.darkGray);
        * g.fillRect(x + 16, y + 7, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 17, y + 7, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 18, y + 7, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 19, y + 7, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 20, y + 7, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 21, y + 7, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 9, y + 8, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 11, y + 8, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 8, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 13, y + 8, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 14, y + 8, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 15, y + 8, 1, 1);
        * g.setColor(Color.darkGray);
        * g.fillRect(x + 16, y + 8, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 17, y + 8, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 18, y + 8, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 19, y + 8, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 20, y + 8, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 21, y + 8, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 22, y + 8, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 10, y + 9, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 11, y + 9, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 9, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 13, y + 9, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 14, y + 9, 1, 1);
        * g.setColor(Color.darkGray);
        * g.fillRect(x + 15, y + 9, 1, 1);
        * g.setColor(Color.darkGray);
        * g.fillRect(x + 16, y + 9, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 17, y + 9, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 18, y + 9, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 19, y + 9, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 20, y + 9, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 9, y + 10, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 11, y + 10, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 10, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 13, y + 10, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 14, y + 10, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 15, y + 10, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 16, y + 10, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 17, y + 10, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 18, y + 10, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 19, y + 10, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 20, y + 10, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 21, y + 10, 1, 1);
        * g.setColor(Color.YELLOW);
        * g.fillRect(x + 22, y + 10, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 11, y + 11, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 12, y + 11, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 13, y + 11, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 14, y + 11, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 15, y + 11, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 16, y + 11, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 17, y + 11, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 18, y + 11, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 19, y + 11, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 20, y + 11, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 11, y + 12, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 12, y + 12, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 13, y + 12, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 14, y + 12, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 17, y + 12, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 18, y + 12, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 19, y + 12, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 20, y + 12, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 11, y + 13, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 12, y + 13, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 13, y + 13, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 14, y + 13, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 15, y + 13, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 16, y + 13, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 17, y + 13, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 18, y + 13, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 19, y + 13, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 20, y + 13, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 14, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 13, y + 14, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 14, y + 14, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 15, y + 14, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 16, y + 14, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 17, y + 14, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 18, y + 14, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 19, y + 14, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 14, y + 15, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 15, y + 15, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 16, y + 15, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 17, y + 15, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 15, y + 16, 1, 1);
        * g.setColor(Color.MAGENTA);
        * g.fillRect(x + 16, y + 16, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 6, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 8, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 9, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 10, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 11, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 12, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 13, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 14, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 15, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 16, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 17, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 18, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 19, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 20, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 21, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 22, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 24, y + 17, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 18, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 4, y + 18, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 5, y + 18, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 6, y + 18, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 18, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 18, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 18, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 24, y + 18, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 25, y + 18, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 26, y + 18, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 18, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 19, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 19, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 19, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 19, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 19, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 20, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 20, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 20, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 20, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 20, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 21, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 21, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 21, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 21, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 21, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 22, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 22, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 22, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 22, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 22, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 23, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 23, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 23, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 23, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 23, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 24, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 24, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 24, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 24, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 24, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 8, y + 24, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 24, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 10, y + 24, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 24, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 24, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 24, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 14, y + 24, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 24, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 16, y + 24, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 24, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 18, y + 24, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 19, y + 24, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 24, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 21, y + 24, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 22, y + 24, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 24, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 24, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 24, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 24, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 24, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 25, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 25, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 8, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 25, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 10, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 25, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 14, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 25, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 16, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 25, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 18, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 25, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 21, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 25, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 25, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 25, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 25, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 26, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 26, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 26, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 26, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 26, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 8, y + 26, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 26, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 10, y + 26, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 26, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 26, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 26, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 14, y + 26, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 26, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 16, y + 26, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 26, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 18, y + 26, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 19, y + 26, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 26, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 21, y + 26, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 26, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 26, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 26, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 26, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 26, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 26, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 27, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 27, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 27, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 27, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 27, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 8, y + 27, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 27, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 10, y + 27, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 27, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 27, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 27, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 14, y + 27, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 27, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 16, y + 27, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 27, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 18, y + 27, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 27, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 27, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 21, y + 27, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 22, y + 27, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 27, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 27, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 27, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 27, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 27, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 28, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 28, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 8, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 28, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 10, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 28, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 28, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 14, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 28, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 16, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 28, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 18, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 28, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 22, y + 28, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 28, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 28, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 28, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 29, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 29, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 9, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 29, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 12, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 29, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 15, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 29, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 18, y + 29, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 19, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 29, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 21, y + 29, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 22, y + 29, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 29, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 29, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 29, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 30, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 30, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 30, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 30, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 30, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 31, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 31, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 31, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 31, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 31, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 32, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 32, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 32, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 32, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 32, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 33, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 33, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 33, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 33, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 33, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 34, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 34, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 34, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 34, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 34, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 35, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 35, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 35, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 35, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 35, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 36, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 36, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 36, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 36, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 36, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 37, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 37, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 37, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 37, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 37, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 38, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 38, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 38, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 38, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 38, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 39, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 39, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 39, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 39, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 39, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 4, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 5, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 6, y + 40, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 40, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 24, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 25, y + 40, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 26, y + 40, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 40, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 3, y + 41, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 4, y + 41, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 5, y + 41, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 6, y + 41, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 7, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 41, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 41, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 23, y + 41, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 24, y + 41, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 25, y + 41, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 26, y + 41, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 27, y + 41, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 4, y + 42, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 5, y + 42, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 6, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 8, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 9, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 10, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 11, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 12, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 13, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 14, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 15, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 16, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 17, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 18, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 19, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 20, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 21, y + 42, 1, 1);
        * g.setColor(Color.RED);
        * g.fillRect(x + 22, y + 42, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 24, y + 42, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 25, y + 42, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 26, y + 42, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 3, y + 43, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 4, y + 43, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 5, y + 43, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 6, y + 43, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 7, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 8, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 9, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 10, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 11, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 12, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 13, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 14, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 15, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 16, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 17, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 18, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 19, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 20, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 21, y + 43, 1, 1);
        * g.setColor(Color.BLACK);
        * g.fillRect(x + 22, y + 43, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 23, y + 43, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 24, y + 43, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 25, y + 43, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 26, y + 43, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 27, y + 43, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 3, y + 44, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 4, y + 44, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 5, y + 44, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 6, y + 44, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 7, y + 44, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 44, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 44, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 44, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 44, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 44, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 44, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 44, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 44, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 44, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 44, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 44, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 44, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 23, y + 44, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 24, y + 44, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 25, y + 44, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 26, y + 44, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 27, y + 44, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 3, y + 45, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 4, y + 45, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 5, y + 45, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 6, y + 45, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 7, y + 45, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 45, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 45, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 45, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 45, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 45, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 45, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 45, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 45, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 45, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 45, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 45, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 45, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 23, y + 45, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 24, y + 45, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 25, y + 45, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 26, y + 45, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 27, y + 45, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 3, y + 46, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 5, y + 46, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 7, y + 46, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 46, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 46, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 46, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 46, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 46, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 46, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 46, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 46, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 46, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 46, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 46, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 46, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 23, y + 46, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 25, y + 46, 1, 1);
        * g.setColor(Color.WHITE);
        * g.fillRect(x + 27, y + 46, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 47, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 47, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 47, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 47, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 47, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 47, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 47, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 47, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 47, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 47, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 47, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 47, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 48, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 48, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 48, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 48, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 48, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 48, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 48, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 48, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 48, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 48, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 48, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 48, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 49, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 49, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 49, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 49, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 49, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 49, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 49, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 49, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 49, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 49, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 49, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 49, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 50, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 50, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 50, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 50, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 50, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 50, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 50, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 50, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 50, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 50, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 50, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 50, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 51, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 51, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 51, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 51, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 51, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 51, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 51, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 51, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 51, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 51, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 51, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 51, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 52, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 52, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 52, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 52, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 52, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 52, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 52, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 52, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 52, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 52, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 52, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 52, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 53, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 53, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 53, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 53, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 53, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 53, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 53, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 53, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 53, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 53, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 53, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 53, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 54, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 54, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 54, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 54, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 54, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 54, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 54, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 54, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 54, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 54, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 54, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 54, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 55, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 55, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 55, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 55, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 55, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 55, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 55, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 55, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 55, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 55, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 55, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 55, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 56, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 56, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 56, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 56, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 56, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 56, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 56, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 56, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 56, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 56, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 56, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 56, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 57, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 57, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 57, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 57, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 57, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 57, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 57, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 57, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 57, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 57, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 57, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 57, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 58, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 58, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 58, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 58, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 58, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 58, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 58, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 58, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 58, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 58, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 58, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 58, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 8, y + 59, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 9, y + 59, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 10, y + 59, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 11, y + 59, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 12, y + 59, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 13, y + 59, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 17, y + 59, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 18, y + 59, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 19, y + 59, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 20, y + 59, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 21, y + 59, 1, 1);
        * g.setColor(Color.BLUE);
        * g.fillRect(x + 22, y + 59, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 8, y + 60, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 9, y + 60, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 10, y + 60, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 11, y + 60, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 12, y + 60, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 13, y + 60, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 17, y + 60, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 18, y + 60, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 19, y + 60, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 20, y + 60, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 21, y + 60, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 22, y + 60, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 8, y + 61, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 9, y + 61, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 10, y + 61, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 11, y + 61, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 12, y + 61, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 13, y + 61, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 17, y + 61, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 18, y + 61, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 19, y + 61, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 20, y + 61, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 21, y + 61, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 22, y + 61, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 7, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 8, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 9, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 10, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 11, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 12, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 13, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 14, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 16, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 17, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 18, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 19, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 20, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 21, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 22, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 23, y + 62, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 7, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 8, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 9, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 10, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 11, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 12, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 13, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 14, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 16, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 17, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 18, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 19, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 20, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 21, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 22, y + 63, 1, 1);
        * g.setColor(Color.GREEN);
        * g.fillRect(x + 23, y + 63, 1, 1);
    	 */
        
    }
    
    
    
}
